---
# tasks file for roles/dns_common

- name: Install dnsmasq
  ansible.builtin.apt:
    name: dnsmasq
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Stop and disable systemd-resolved
  ansible.builtin.systemd:
    name: systemd-resolved
    state: stopped
    enabled: false
    masked: true
  tags:
    - skip_ansible_lint
  ignore_errors: true

- name: Configure resolv.conf
  ansible.builtin.template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: "0644"

- name: Ensure hostname entry exists in /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "127.0.0.1 {{ ansible_hostname }}"
    state: present

- name: Deploy dnsmasq configuration
  ansible.builtin.template:
    src: 10-consul.conf.j2
    dest: /etc/dnsmasq.d/10-consul.conf
    mode: "0755"
  notify: Restart dnsmasq

- name: Ensure dnsmasq service is running and enabled
  ansible.builtin.systemd:
    name: dnsmasq
    state: started
    enabled: true
