---
# defaults file for roles/kubernetes
kubernetes_prerequisites_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg2
  - lsb-release
  - bridge-utils
kubernetes_minor_version: "1.30"
kubernetes_version: "{{ kubernetes_minor_version }}.3-1.1"
kubernetes_cidr_pods: "10.200.0.0/16"
kubernetes_cidr_services: "10.201.0.0/16"
kubeadm_init_master: "diypcp-k8sm1"
kubeadm_master_group_name: "meta-app_k8sm"
kubeadm_worker_group_name: "meta-app_k8sw"
kubernetes_consul_group: "meta-app_consul"
kubernetes_api_endpoint: "k8s-apiserver.service.consul"
kubernetes_api_cert_sans: "k8s-apiserver.service.consul"
