repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.23.1
    hooks:
      - id: gitleaks
  - repo: https://github.com/bridgecrewio/checkov.git
    rev: '3.2.386'
    hooks:
      - id: checkov
        files: \.y(a)?ml$
        entry: checkov -d ansible -d terraform --quiet