[tools]
python = "3.11"

[env]
_.python.venv = ".venv"

[tasks.tf-vpn-init]
run = "cd terraform/vpn && terraform init -backend-config=../backend.conf"

[tasks.tf-lint]
run = "cd terraform/vpn && tflint"

[tasks.tf-fmt]
run = "cd terraform/vpn && terraform fmt"

[tasks.ansible-lint]
run = "cd ansible && ansible-lint"

[tasks.ansible-install]
run = """
cd ansible
ansible-galaxy collection install openstack.cloud
ansible-galaxy collection install community.general
"""

[tasks.ansible-inventory]
run = "cd ansible && ansible-inventory -i openstack.yml --list"
