[tools]
python = "3.11"

[env]
_.python.venv = ".venv"

[tasks.pre-commit-init]
run = "pre-commit install"

[tasks.tf-vpn-init]
run = "cd terraform/vpn && terraform init -backend-config=../backend.conf"

[tasks.tf-infra-init]
run = "cd terraform/infra && terraform init -backend-config=../backend.conf"

[tasks.tf-backup-init]
run = "cd terraform/backup && terraform init -backend-config=../backend.conf"

[tasks.tf-lint]
run = """
echo 'Running tflint on terraform/vpn...'
(cd terraform/vpn && tflint)
echo 'Running tflint on terraform/infra...'
(cd terraform/infra && tflint)
echo 'Running tflint on terraform/backup...'
(cd terraform/backup && tflint)
echo 'Running tflint on terraform/modules/openstack_instance...'
(cd terraform/modules/openstack_instance && tflint)
echo 'Running tflint on terraform/modules/openstack_network...'
(cd terraform/modules/openstack_network && tflint)
"""

[tasks.tf-fmt]
run = """
echo 'Running terraform fmt on terraform/vpn...'
(cd terraform/vpn && terraform fmt)
echo 'Running terraform fmt on terraform/infra...'
(cd terraform/infra && terraform fmt)
echo 'Running terraform fmt on terraform/backup...'
(cd terraform/backup && terraform fmt)
echo 'Running terraform fmt on terraform/modules/openstack_instance...'
(cd terraform/modules/openstack_instance && terraform fmt)
echo 'Running terraform fmt on terraform/modules/openstack_network...'
(cd terraform/modules/openstack_network && terraform fmt)
"""

[tasks.ansible-lint]
run = "cd ansible && ansible-lint"

[tasks.ansible-install]
run = """
cd ansible
ansible-galaxy collection install openstack.cloud
ansible-galaxy collection install community.general
ansible-galaxy collection install devsec.hardening
"""

[tasks.ansible-inventory]
run = "cd ansible && ansible-inventory -i openstack.yml --list"

[tasks.ansible-all]
run = "cd ansible && ANSIBLE_CONFIG=ansible.cfg ansible-playbook -u clouduser -i openstack.yml pb_all.yml"
depends = "ansible-inventory"

[tasks.ansible-consul]
run = "cd ansible && ANSIBLE_CONFIG=ansible.cfg ansible-playbook -u clouduser -i openstack.yml -e @./envs/sandbox/group_vars/meta-app_consul.yml pb_consul.yml"
depends = "ansible-all"

[tasks.ansible-all-consul-services]
run = "cd ansible && ANSIBLE_CONFIG=ansible.cfg ansible-playbook -u clouduser -i openstack.yml pb_all_consul_services.yml"
depends = "ansible-consul"

[tasks.ansible-traefik]
run = "cd ansible && ANSIBLE_CONFIG=ansible.cfg ansible-playbook -u clouduser -i openstack.yml -e @./envs/sandbox/group_vars/meta-app_traefik.yml pb_traefik.yml"
depends = "ansible-all-consul-services"

[tasks.ansible-monitoring]
run = "cd ansible && ANSIBLE_CONFIG=ansible.cfg ansible-playbook -u clouduser -i openstack.yml -e @./envs/sandbox/group_vars/domains.yml  pb_monitoring.yml"
depends = "ansible-all-consul-services"

[tasks.ansible-logging]
run = "cd ansible && ANSIBLE_CONFIG=ansible.cfg ansible-playbook -u clouduser -i openstack.yml pb_logging.yml"
depends = "ansible-monitoring"

[tasks.ansible-all-hardening]
run = "cd ansible && ANSIBLE_CONFIG=ansible.cfg ansible-playbook -u clouduser -i openstack.yml pb_all_hardening.yml"
depends = "ansible-all"
