---
# tasks file for roles/vmagent

- name: Check if vmagent exists
  ansible.builtin.stat:
    path: /usr/local/bin/vmagent-prod
  register: __vmagent_exists

- name: If vmagent exists get version
  ansible.builtin.shell: "cat /etc/systemd/system/vmagent.service | grep Version | sed s/'.*Version '//g"
  register: __get_vmagent_version
  when: __vmagent_exists.stat.exists
  tags:
    - skip_ansible_lint
  changed_when: false

- name: Create directory for vmagent data
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0750
    recurse: yes
  loop:
    - "{{ vmagent_dir_config }}"
    - "{{ vmagent_dir_data }}"

- name: Download vmstack
  ansible.builtin.unarchive:
    src: https://github.com/VictoriaMetrics/VictoriaMetrics/releases/download/v{{ vmagent_version }}/vmutils-linux-amd64-v{{ vmagent_version }}.tar.gz
    dest: /usr/local/bin
    remote_src: yes
  when: not __vmagent_exists.stat.exists or not __get_vmagent_version.stdout == vmagent_version

- name: Vmagent configuration file
  ansible.builtin.template:
    src: "vmagent.service.j2"
    dest: "/etc/systemd/system/vmagent.service"
    mode: 0750
  notify: "Restart vmagent"

- name: Vmagent configuration file
  ansible.builtin.template:
    src: vmagent.yml.j2
    dest: "{{ vmagent_dir_config }}/vmagent.yml"
    mode: 0750
  notify: Restart vmagent

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Start vmagent
  ansible.builtin.systemd:
    name: vmagent
    state: started
    enabled: yes
