- name: Add stable chart repo
  kubernetes.core.helm_repository:
    name: prometheus
    repo_url: "https://prometheus-community.github.io/helm-charts"

- name: Deploy consul exporter
  kubernetes.core.helm:
    name: consul-exporter
    chart_ref: prometheus/prometheus-consul-exporter
    chart_version: "{{ kubernetes_monitoring_consul_exporter_version }}"
    release_namespace: monitoring
    create_namespace: true
    values: "{{ lookup('template', 'consul-exporter-values.yaml.j2') | from_yaml }}"
