---
# tasks file for roles/vmtools

- name: Check if vmagent exists
  ansible.builtin.stat:
    path: /usr/local/bin/vmagent-prod
  register: __vmagent_exists

- name: Check if vmalert exists
  ansible.builtin.stat:
    path: /usr/local/bin/vmalert-prod
  register: __vmalert_exists

- name: If vmagent exists get version
  ansible.builtin.shell: "cat /etc/systemd/system/vmagent.service | grep Version | sed s/'.*Version '//g"
  register: __get_vmagent_version
  when: __vmagent_exists.stat.exists
  tags:
    - skip_ansible_lint
  changed_when: false

- name: Create directory for vmagent data
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0750
    recurse: yes
  loop:
    - "{{ vmtools_vmagent_dir_config }}"
    - "{{ vmtools_vmagent_dir_data }}"
    - "{{ vmtools_vmalert_dir_config }}"

- name: Download vmtools
  ansible.builtin.unarchive:
    src: https://github.com/VictoriaMetrics/VictoriaMetrics/releases/download/v{{ vmtools_version }}/vmutils-linux-amd64-v{{ vmtools_version }}.tar.gz
    dest: /usr/local/bin
    remote_src: yes
  when: not __vmagent_exists.stat.exists or not __get_vmagent_version.stdout == vmtools_version or not __vmalert_exists.stat.exists

- name: Vmagent configuration file
  ansible.builtin.template:
    src: vmagent.yml.j2
    dest: "{{ vmtools_vmagent_dir_config }}/vmagent.yml"
    mode: 0750
  notify: "RESTART_vmagent"

- name: Vmalert alerts configuration files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/vmalert/{{ item | basename }}"
    mode: 0750
  notify: "RESTART_vmalert"
  with_fileglob:
    - alerts/*.yml

- name: "Vmtools services - {{ item }} "
  ansible.builtin.template:
    src: "{{ item }}.service.j2"
    dest: "/etc/systemd/system/{{ item }}.service"
    mode: 0750
  notify: "RESTART_{{ item }}"
  loop:
    - vmagent
    - vmalert

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Start vmtools
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - vmagent
    - vmalert
