kubernetes_monitoring_stack_version: "62.3.1"
kubernetes_monitoring_stack_retention: "4h"
kubernetes_monitoring_stack_sc: "csi-cinder-sc-delete"
kubernetes_monitoring_stack_storage_size: "20Gi"
kubernetes_monitoring_prom_replicas: 2
kubernetes_monitoring_prom_remote_write: "http://vminsert-victoriametrics.monitoring.svc.cluster.local:8480/insert/0/prometheus/api/v1/write"
kubernetes_monitoring_grafana_ds_vmetrics_url: "http://vmselect-victoriametrics.monitoring.svc.cluster.local:8481/select/0/prometheus"
kubernetes_monitoring_grafana_domain:

kubernetes_monitoring_vmcluster_name: "victoriametrics"
kubernetes_monitoring_vmoperator_stack_version: "0.50.3"
kubernetes_monitoring_vmcluster_namespace: "monitoring"
kubernetes_monitoring_vmcluster_vmselect_replicas: "2"
kubernetes_monitoring_vmcluster_vminsert_replicas: "2"
kubernetes_monitoring_vmcluster_vmstorage_replicas: "2"
kubernetes_monitoring_vmcluster_vmstorage_retention: "1y"
kubernetes_monitoring_vmcluster_vmselect_size: "2Gi"
kubernetes_monitoring_vmcluster_vmstorage_size: "20Gi"
kubernetes_monitoring_vmcluster_vmstorage_storageclass: "csi-cinder-sc-delete"
kubernetes_monitoring_vmcluster_vmselect_storageclass: "csi-cinder-sc-delete"

kubernetes_monitoring_consul_exporter_version: "1.0.0"
kubernetes_monitoring_consul_exporter_server: "consul.service.consul:8500"

kubernetes_monitoring_vmcluster_vlogs_retention: "1y"
kubernetes_monitoring_vmcluster_vlogs_size: "30Gi"
kubernetes_monitoring_vmcluster_vlogs_storageclass: "csi-cinder-sc-delete"
kubernetes_monitoring_grafana_ds_vlogs_url: http://vlogs-vlogs.service.consul:9428
