---
# tasks file for roles/consul_services

- name: Check if consul exists
  ansible.builtin.stat:
    path: /usr/local/bin/consul
  register: __consul_installed

- name: Check prerequites
  ansible.builtin.assert:
    that:
      - __consul_installed.stat.exists == true
    fail_msg: "Failed : you need to install consul before. Add the role please."

- name: Render services
  ansible.builtin.template:
    src: service_consul.json.j2
    dest: "/etc/consul.d/{{ item.name }}.json"
    mode: 0750
    owner: consul
    group: consul
  with_items: "{{ consul_services_list }}"
  notify: Reload consul
  when: consul_services_list

- name: Remove a service
  ansible.builtin.file:
    path: "/etc/consul.d/{{ item }}.json"
    state: absent
  with_items: "{{ consul_services_remove }}"
  when: consul_services_remove is defined
