---
# tasks file for roles/openvpn_client

- name: "Create client - {{ item }}"
  ansible.builtin.include_tasks:
    file: create_client.yml
  loop: "{{ openvpn_client_user_list }}"
  loop_control:
    loop_var: item
  tags:
    - fetch
