vector_dir_data: "/var/lib/vector"
vector_dir_config: "/etc/vector"
vector_version: 0.46.1
vector_binary_path: "/usr/local/bin/"
# when using vector with loki
# vector_loki_endpoint: loki.service.consul:3100
# when using vector with vmetrics
vector_loki_endpoint: "vlogs-vlogs.service.consul:9428/insert/loki/"
vector_loki_path: /api/v1/push?_msg_field=message&_time_field=timestamp&_stream_fields=source

vector_specifics_list: []
