# https://developer.hashicorp.com/consul/docs/reference/k8s/helm
- name: Deploy consul sync
  kubernetes.core.helm:
    name: consul
    chart_ref: hashicorp/consul
    chart_version: 0.45.0
    release_namespace: sre
    create_namespace: true
    values: "{{ lookup('template', 'consulsync-values.yml.j2') | from_yaml }}"
