- name: Install helm if not exists
  ansible.builtin.unarchive:
    src: "https://get.helm.sh/helm-v{{ kubernetes_tooling_helm_version }}-linux-amd64.tar.gz"
    dest: /usr/local/bin
    extra_opts: "--strip-components=1"
    owner: root
    group: root
    mode: 0755
    remote_src: true
  args:
    creates: /usr/local/bin/helm

- name: Add stable chart repo
  kubernetes.core.helm_repository:
    name: hashicorp
    repo_url: "https://helm.releases.hashicorp.com"

- name: Deploy consul sync
  ansible.builtin.include_tasks: consul_sync.yml

- name: Deploy cinder-csi
  ansible.builtin.include_tasks: cinder_csi.yml
