- name: Consul_master
  hosts: meta-app_consul
  roles:
    - common/volumes
    - consul/consul
    - common/backup
    - monitoring/metrics_task_times
  become: true
  vars:
    consul_master: true
    consul_dir_master_data: "/data"
    volumes_disks:
      - {
          disk: "/dev/sdb",
          path: "{{ consul_dir_master_data }}",
          owner: "consul",
        }

- name: Consul agent
  hosts: all,!meta-app_consul
  roles:
    - consul/consul
  become: true
