- name: Consul_master
  hosts: meta-app_consul
  become: true
  vars:
    consul_master: true
    consul_dir_master_data: "/data"
    volumes_disks:
      - {
          disk: "/dev/sdb",
          path: "{{ consul_dir_master_data }}",
          owner: "consul",
        }
  roles:
    - volumes
    - consul
- name: Consul agent
  hosts: all,!meta-app_consul
  become: true
  roles:
    - consul
