- name: Logging
  become: yes
  hosts: meta-app_monitoring
  # Uncomment the following line if you deploy loki as an standalone instance
  # hosts: meta-app_loki
  roles:
    - common/volumes
    - logging/loki
    - consul/consul_services
  vars:
    volumes_disks:
      # Uncomment the following line if you deploy loki as an standalone instance
      # - { disk: "/dev/sdb", path: "/data", owner: "loki" }
      - { disk: "/dev/sdc", path: "/data_loki", owner: "loki" }
    consul_services_list:
      - {
          name: "loki",
          type: "http",
          check_target: "http://127.0.0.1:3100/metrics",
          interval: "10s",
          port: 3100,
        }
