- name: Monitoring
  become: yes
  hosts: meta-app_monitoring
  roles:
    - volumes
    - vmtools
    - vmetrics
    - consul_services
  vars:
    vmtools_dir_disk_data: "/data"
    vmetrics_dir_disk_data: "/data"
    vmtools_vmalert_remote: vmetrics.service.sandbox.consul
    vmtools_vmalert_grafana: grafana.service.sandbox.consul
    volumes_disks:
      - { disk: "/dev/sdb", path: "{{ vmtools_dir_disk_data }}" }
    consul_services_list:
      - {
          name: "vmagent",
          type: "http",
          check_target: "http://127.0.0.1:8429",
          interval: "20s",
          port: 8429,
        }
      - {
          name: "vmetrics",
          type: "http",
          check_target: "http://127.0.0.1:8428",
          interval: "20s",
          port: 8428,
        }
      - {
          name: "vmalert",
          type: "http",
          check_target: "http://127.0.0.1:8880",
          interval: "20s",
          port: 8880,
        }
