- name: Monitoring
  become: yes
  hosts: meta-app_monitoring
  roles:
    - common/volumes
    - monitoring/vmtools
    - monitoring/vmetrics
    - monitoring/alertmanager
    - monitoring/karma
    - monitoring/grafana
    - consul/consul_services
    - monitoring/consul_exporter
  vars:
    vmtools_dir_disk_data: "/data"
    vmetrics_dir_disk_data: "/data"
    vmtools_vmalert_remote: vmetrics.service.sandbox.consul
    vmtools_vmalert_grafana: grafana.service.sandbox.consul
    karma_alertmanager_uri: "http://alertmanager.service.sandbox.consul:9093"
    grafana_prometheus_address: "vmetrics.service.sandbox.consul:8428"
    grafana_datasources:
      - {
          name: "VictoriaMetrics",
          type: "prometheus",
          address: "vmetrics.service.consul:8428",
          uid: "vmetrics",
        }
      - {
          name: "Loki",
          type: "loki",
          address: "loki.service.consul:3100",
          uid: "loki",
        }
    grafana_dashboards:
      - {
          label: "node-exporter",
          json_url: "https://raw.githubusercontent.com/rfrail3/grafana-dashboards/master/prometheus/node-exporter-full.json",
          mode: "web",
        }
      - { label: "backups", json: "backups.json", mode: "local" }
      - { label: "errorlog", json: "errorlog.json", mode: "local" }
      - { label: "traefik", json: "traefik.json", mode: "local" }
      - { label: "consul", json: "consul.json", mode: "local" }
      - { label: "postgres", json: "postgres.json", mode: "local" }

    volumes_disks:
      - { disk: "/dev/sdb", path: "{{ vmtools_dir_disk_data }}" }
    consul_services_list:
      - {
          name: "vmagent",
          type: "http",
          check_target: "http://127.0.0.1:8429",
          interval: "20s",
          port: 8429,
        }
      - {
          name: "vmetrics",
          type: "http",
          check_target: "http://127.0.0.1:8428",
          interval: "20s",
          port: 8428,
          tags:
            [
              "traefik.enable=true",
              "traefik.http.routers.router-vmetrics.entrypoints=http,https",
              "traefik.http.routers.router-vmetrics.rule=Host(`{{ vmetrics_domain }}`)",
              "traefik.http.routers.router-vmetrics.service=vmetrics",
              "traefik.http.routers.router-vmetrics.middlewares=auth@file,to_https@file,secure_headers@file",
              "traefik.http.routers.router-vmetrics.tls.certresolver=certs_gen",
            ],
        }
      - {
          name: "vmalert",
          type: "http",
          check_target: "http://127.0.0.1:8880",
          interval: "20s",
          port: 8880,
        }
      - {
          name: "alertmanager",
          type: "http",
          check_target: "http://127.0.0.1:9093",
          interval: "20s",
          port: 9093,
        }
      - {
          name: "karma",
          type: "http",
          check_target: "http://127.0.0.1:8080",
          interval: "10s",
          port: 8080,
        }
      - {
          name: "grafana",
          type: "http",
          check_target: "http://127.0.0.1:3000",
          interval: "10s",
          port: 3000,
          tags:
            [
              "traefik.enable=true",
              "traefik.http.routers.router-grafana.entrypoints=http,https",
              "traefik.http.routers.router-grafana.rule=Host(`{{ grafana_domain }}`)",
              "traefik.http.routers.router-grafana.service=grafana",
              "traefik.http.routers.router-grafana.middlewares=auth@file,to_https@file,secure_headers@file",
              "traefik.http.routers.router-grafana.tls.certresolver=certs_gen",
            ],
        }
      - {
          name: "consul_exporter",
          type: "http",
          check_target: "http://127.0.0.1:9107",
          interval: "20s",
          port: 9107,
        }
