- name: Install our postgresql cluster
  become: yes
  hosts: meta-app_postgresql
  roles:
    - common/volumes
    - postgresql/postgresql_simple
    - monitoring/postgresql_exporter
    - consul/consul_services
  vars:
    volumes_disks:
      - { disk: "/dev/sdb", path: "/data", owner: "root", mode: "0755" }
    postgresql_simple_data_dir: /data/postgresql
    postgresql_simple_pghba_enabled: false
    consul_services_list:
      - {
          name: "postgresql",
          type: "tcp",
          check_target: "127.0.0.1:5432",
          interval: "10s",
          port: 5432,
        }
      - {
          name: "postgresql_exporter",
          type: "tcp",
          check_target: "127.0.0.1:9187",
          interval: "10s",
          port: 9187,
        }

- name: Install our postgresql replication
  become: yes
  hosts: diypcp-postgresql1,diypcp-postgresql2
  serial: 1
  roles:
    - postgresql/postgresql_replication
    - consul/consul_services
  vars:
    postgresql_replication_data_dir: "/data/postgresql"
    postgresql_replication_group: "meta-app_postgresql"
    postgresql_replication_pattern: "diypcp-postgresql"
    postgresql_replication_primary: "diypcp-postgresql1"
    postgresql_replication_pghba_entries:
      - {
          host: "host",
          database: "{{ postgresql_manage_mattermost_database }}",
          user: "all",
          address: "10.0.1.0/24",
          method: "md5",
        }
      - {
          host: "host",
          database: "{{ postgresql_manage_keycloak_database }}",
          user: "all",
          address: "10.0.1.0/24",
          method: "scram-sha-256",
        }
    consul_services_list:
      - {
          name: "postgresql_primary",
          type: "args",
          check_target: "/opt/failover_postgresql.sh",
          interval: "10s",
          port: 5432,
        }

- name: Postgresql management
  become: yes
  hosts: diypcp-postgresql1
  roles:
    - postgresql/postgresql_manage
  vars:
    postgresql_manage:
      users:
        - {
            name: "{{ postgresql_manage_mattermost_username }}",
            password: "{{ postgresql_manage_mattermost_password }}",
          }
        - {
            name: "{{ postgresql_manage_keycloak_username }}",
            password: "{{ postgresql_manage_keycloak_password }}",
          }
      db_name:
        - "{{ postgresql_manage_mattermost_database }}"
        - "{{ postgresql_manage_keycloak_database }}"
      privileges:
        - {
            db: "{{ postgresql_manage_mattermost_database }}",
            type: "database",
            user: "{{ postgresql_manage_mattermost_username }}",
            permissions: "ALL",
          }
        - {
            db: "{{ postgresql_manage_keycloak_database }}",
            type: "database",
            user: "{{ postgresql_manage_keycloak_username }}",
            permissions: "ALL",
          }
      privileges_schema:
        - {
            schemas_name: "public",
            owner: "{{ postgresql_manage_mattermost_username }}",
            db: "{{ postgresql_manage_mattermost_database }}",
          }
        - {
            schemas_name: "public",
            owner: "{{ postgresql_manage_keycloak_username }}",
            db: "{{ postgresql_manage_keycloak_database }}",
          }

- name: Postgresql primary backup
  become: yes
  hosts: diypcp-postgresql1
  roles:
    - common/backup
    - monitoring/metrics_task_times
  vars:
    backup_app: "postgresql"

- name: Postgresql primary backup wall-g
  become: yes
  hosts: diypcp-postgresql1
  roles:
    - postgresql/postgresql_pitr_wallg
  vars:
    postgresql_pitr_wallg_pg_datadir: "/data/postgresql"
