---
postgresql_manage_keycloak_password:
postgresql_manage_keycloak_username:
postgresql_manage_keycloak_database:

keycloak_admin_user_username:
keycloak_admin_user_password:
keycloak_keystore_secret:

keycloak_realm:
keycloak_grafana_client_id:
keycloak_grafana_client_secret:

keycloak_user1_username:
keycloak_user1_firstname:
keycloak_user1_lastname:
keycloak_user1_email:
keycloak_user1_password: