---
openvpn_server_name:
openvpn_key_name:
openvpn_key_country:
openvpn_key_province:
openvpn_key_city:
openvpn_key_org:
openvpn_key_email:
openvpn_key_ou:

openvpn_client_user_list:
  - 
openvpn_client_destination_key: