dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: server-test
    hostname: server-test
    image: debian:bookworm
    privileged: true
provisioner:
  name: ansible
verifier:
  name: testinfra