- name: Ensure psycopg2 installed
  ansible.builtin.apt:
    name: python3-psycopg2
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Create user {{ item.name }}
  become_user: postgres
  become: true
  community.postgresql.postgresql_user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    encrypted: true
  loop: "{{ postgresql_manage.users }}"
  when: postgresql_manage.users is defined
  no_log: true

- name: Create database {{ item }}
  become_user: postgres
  become: true
  community.postgresql.postgresql_db:
    name: "{{ item }}"
    owner: "postgres"
  loop: "{{ postgresql_manage.db_name }}"
  when: postgresql_manage.db_name is defined

- name: Privileges database {{ item.user }} - {{ item.permissions }}
  become_user: postgres
  become: true
  community.postgresql.postgresql_privs:
    db: "{{ item.db }}"
    type: "{{ item.type }}"
    privs: "{{ item.permissions }}"
    roles: "{{ item.user }}"
  loop: "{{ postgresql_manage.privileges }}"
  when: postgresql_manage.privileges is defined
  tags:
    - skip_ansible_lint

- name: Create schema {{ item.schemas_name }}
  become_user: postgres
  become: true
  community.postgresql.postgresql_schema:
    name: "{{ item.schemas_name }}"
    owner: "{{ item.owner }}"
    database: "{{ item.db }}"
  loop: "{{ postgresql_manage.privileges_schema }}"
  when: postgresql_manage.privileges_schema is defined
