name: CI Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' 

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.11.1"

      - name: Install Dependencies
        run: |
          pip install -q checkov==3.2.408 ansible-lint ansible
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
          curl https://mise.run | sh
          checkov --version
          ansible-lint --version
          tflint --version
          mise --version

      - name: Install Ansible collections
        run: mise run ansible-install

      - name: Run TFLint
        run: mise run tf-lint
      - name: Run Ansible lint
        run: mise run ansible-lint
      - name: Run Checkov
        run: |
          checkov -d terraform --framework terraform --quiet
          checkov -d ansible --framework ansible --quiet  --skip-path ansible/envs --skip-path ansible/.ansible