name: CI Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' 

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.11.1"

      - name: Install Dependencies
        run: |
          pip install -q checkov==3.2.408 ansible-lint ansible
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
          checkov --version
          ansible-lint --version
          tflint --version

      - name: Install Ansible collections
        run: make ansible-install

      - name: Init tf modules
        run: |
          (cd terraform/backup && terraform init -backend=false)
          (cd terraform/infra && terraform init -backend=false)
          (cd terraform/vpn && terraform init -backend=false)
          (cd terraform/modules/openstack_instance && terraform init -backend=false)
          (cd terraform/modules/openstack_network && terraform init -backend=false)

      - name: Run TFLint
        run: make tf-lint

      - name: Run Terraform validate
        run: make tf-validate

      - name: Run Terraform tests
        run: make tf-test

      - name: Run Ansible lint
        run: make ansible-lint
        
      - name: Run Checkov
        run: |
          checkov -d terraform --framework terraform --quiet
          checkov -d ansible --framework ansible --quiet  --skip-path ansible/envs --skip-path ansible/.ansible