- name: Converge
  hosts: server-test
  become: true
  vars:
    backup_s3_uri: "backup_s3_uri"
    backup_s3_key: "backup_s3_key"
    backup_s3_aws_region: "backup_s3_aws_region"
    backup_s3_secret_key: "backup_s3_secret_key"
    backup_restic_secret_password: "backup_restic_secret_password"
    backup_cron_schedule: "0 1 * * *"
    backup_log_dir: "/var/log/backups"
    backup_metrics_dir: "/var/lib/metrics_task_times"
    backup_app: "consul"
  roles:
    - ../../roles/common/backup
